### ISSUE TITLE
您好，能否在最上层添加一个按地区选择的组？

### ISSUE THREAD

**Issue by 13810169** [mphin/ACL4SSR#1]
您好，能否在最上层添加一个按地区选择的组，我直接在最上面选择香港，然后所有需要代理的域名都走香港的节点，而且香港节点组内的节点，可以自动按延迟来切换，现在虽然可以实现这样的目的，但是需要我在每个策略组里面手动指定香港才行。

**Comment by mphin** [comment]
已添加
